#!/bin/bash
VIRTUAL_ENV=~/text-to-lora/.venv

# Basic OPPU training without RAG or full history settings

CUDA_VISIBLE_DEVICES=4 uv run python src/hyper_llm_modulator/oppu_trainer.py \
    --dataset_name LaMP_processed_citation_ood_test LaMP_processed_tweet_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_news_headline_ood_test LaMP_processed_product_ood_test LaMP_processed_scholarly_title_ood_test LongLaMP_product_review_ood_test LongLaMP_abstract_generation_ood_test LongLaMP_topic_writing_ood_test \
    LaMP_processed_citation_random_test LaMP_processed_tweet_random_test LaMP_processed_movie_random_test LaMP_processed_news_cat_random_test LaMP_processed_news_headline_random_test LaMP_processed_product_random_test LaMP_processed_scholarly_title_random_test LongLaMP_product_review_random_test LongLaMP_abstract_generation_random_test LongLaMP_topic_writing_random_test \
    --output_dir ./eval_results/Qwen/Qwen2.5-3B-Instruct/oppu_baselines_v9 \
    --model_name "Qwen/Qwen2.5-3B-Instruct" \
    --batch_size 4 \
    --gradient_accumulation_steps 4 \
    --learning_rate 1e-4 \
    --num_epochs 2 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --num_retrieved_examples 0 \
    --max_length 1024 \
    --no_checkpoints \
    --data_version v9 \
    --gradient_checkpointing

    # --use_checkpoints

# LaMP_processed_movie_ood_test LaMP_processed_movie_random_test LaMP_processed_news_cat_ood_test LaMP_processed_product_ood_test LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_news_headline_ood_test LaMP_processed_product_ood_test LaMP_processed_product_ood_test LaMP_processed_scholarly_title_ood_test LongLaMP_product_review_ood_test LongLaMP_abstract_generation_ood_test \
# LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_tweet_random_test LaMP_processed_citation_random_test LaMP_processed_news_cat_random_test LaMP_processed_product_random_test LaMP_processed_tweet_random_test LaMP_processed_citation_random_test LaMP_processed_movie_random_test LaMP_processed_news_cat_random_test LaMP_processed_news_headline_random_test LaMP_processed_product_random_test LaMP_processed_product_random_test LaMP_processed_scholarly_title_random_test LongLaMP_product_review_random_test LongLaMP_abstract_generation_random_test LongLaMP_product_review_random_test LongLaMP_abstract_generation_random_test LongLaMP_topic_writing_random_test \


# LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_product_ood_test LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_news_headline_ood_test LaMP_processed_product_ood_test LaMP_processed_product_ood_test LaMP_processed_scholarly_title_ood_test LongLaMP_product_review_ood_test LongLaMP_abstract_generation_ood_test 
# LaMP_processed_tweet_random_test LaMP_processed_citation_random_test LaMP_processed_movie_random_test LaMP_processed_news_cat_random_test LaMP_processed_product_random_test LaMP_processed_tweet_random_test LaMP_processed_citation_random_test LaMP_processed_movie_random_test LaMP_processed_news_cat_random_test LaMP_processed_news_headline_random_test LaMP_processed_product_random_test LaMP_processed_product_random_test LaMP_processed_scholarly_title_random_test LongLaMP_product_review_random_test LongLaMP_abstract_generation_random_test LongLaMP_topic_generation_random_test LongLaMP_product_review_random_test LongLaMP_abstract_generation_random_test LongLaMP_topic_writing_random_test \
# LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_citation_ood_test LaMP_processed_tweet_ood_test
# LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_product_ood_test LaMP_processed_tweet_ood_test LaMP_processed_citation_ood_test LaMP_processed_movie_ood_test LaMP_processed_news_cat_ood_test LaMP_processed_news_headline_ood_test LaMP_processed_product_ood_test LaMP_processed_product_ood_test LaMP_processed_scholarly_title_ood_test LongLaMP_product_review_ood_test LongLaMP_abstract_generation_ood_test LongLaMP_topic_generation_ood_test LongLaMP_product_review_ood_test LongLaMP_abstract_generation_ood_test LongLaMP_topic_writing_ood_test

# Example with multiple datasets (basic settings only):
# uv run python src/hyper_llm_modulator/oppu_trainer.py \
#     --dataset_name LaMP_processed_movie LaMP_processed_product LaMP_processed_citation \
#     --output_dir ./results/oppu_baselines \
#     --num_retrieved_examples 0 
    
